[package]
name = "aptos-fuzzer"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
memory-stats = "1.1.0"

[dependencies]
bichannel = "0.0.4"
clap = { version = "4.4.4", features = ["derive"] }
ratatui = { version = "0.23.0", features = ["all-widgets"] }
serde = { version = "1.0.188", features = ["derive", "serde_derive"] }
serde_json = "1.0.107"
basic_mutator = { git = "https://github.com/gamozolabs/basic_mutator" }
strum = { version = "0.25", features = ["derive"] }
crossterm = "0.27.0"
time = "0.3.29"
chrono = "0.4.31"
itertools = "0.12.0"
futures = "0.3.30"
tokio = { version = "1.35.1", features = ["full"] }
tokio-core = "0.1.18"
enum-as-inner = "0.6.0"
rand = "0.8.5"
url = "2.0"
ark-std = "0.5.0"
move-package = { path = "./aptos-core/third_party/move/tools/move-package" }
anyhow = "1.0"

# Aptos dependencies
aptos-language-e2e-tests = { path = "./aptos-core/aptos-move/e2e-tests" }
aptos-types = { path = "./aptos-core/types" }
aptos-vm = { path = "./aptos-core/aptos-move/aptos-vm" }
aptos-crypto = {path = "./aptos-core/crates/aptos-crypto"}
aptos-sdk = {path = "./aptos-core/sdk"}
aptos-secure-storage = {path = "./aptos-core/secure/storage"}
move-core-types = { path = "./aptos-core/third_party/move/move-core/types" }
bcs = { git = "https://github.com/movementlabsxyz/bcs.git"}
move-model = {  path = "./aptos-core/third_party/move/move-model" }
aptos-executor = {path = "./aptos-core/execution/executor"}
aptos-executor-types = {path = "./aptos-core/execution/executor-types"}
aptos-block-executor = {path = "./aptos-core/aptos-move/block-executor"}
aptos-storage-interface = {path = "./aptos-core/storage/storage-interface", features = ["fuzzing"]}
aptos-scratchpad = {path = "./aptos-core/storage/scratchpad"}
[features]
default = ["aptos"]
aptos = []

