[package]
name = "aptos-fuzzer"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
memory-stats = "1.1.0"

[dependencies]
bichannel = "0.0.4"
clap = { version = "4.4.4", features = ["derive"] }
ratatui = { version = "0.23.0", features = ["all-widgets"] }
serde = { version = "1.0.188", features = ["derive", "serde_derive"] }
serde_json = "1.0.107"
basic_mutator = { git = "https://github.com/gamozolabs/basic_mutator" }
strum = { version = "0.25", features = ["derive"] }
crossterm = "0.27.0"
time = "0.3.29"
chrono = "0.4.31"
itertools = "0.12.0"
futures = "0.3.30"
tokio = { version = "1.2", features = ["full"] }
tokio-core = "0.1.18"
enum-as-inner = "0.6.0"
rand = "0.8.5"
url = "2.0"
move-package = { git = "https://github.com/movementlabsxyz/move.git", branch = "main" }


# Aptos dependencies
aptos-language-e2e-tests = { path = "./aptos-core/aptos-move/e2e-tests" }
aptos-types = { path = "./aptos-core/types" }
aptos-vm = { path = "./aptos-core/aptos-move/aptos-vm" }
move-core-types = { path = "./aptos-core/third_party/move/move-core/types" }
bcs = { git = "https://github.com/movementlabsxyz/bcs.git"}

[features]
default = ["aptos"]
aptos = []